class Game
  def initialize
    @computer = Computer.new
    @secret_code = @computer.generate_code
    @player = Player.new
  end

  def play
    i = 0
    puts "\nSecret code was randomly generated by the computer"
    p @secret_code
    while i <= 11
      puts "\nPlease insert your guess in Color1-Color2-Color3-Color4 format, where - indicates whitespace."
      player_guess = gets.chomp.split(' ')
      @player.guess(player_guess, @secret_code)
      if player_guess ==  @secret_code
        puts "You have correctly guessed the secret code, congratulations!"
        break
      else
        i += 1
      end
    end
  end
end